version: '3.8'

services:

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'

  # Nginx as Reverse Proxy
  nginx:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - frontend

